#!/bin/sh

set -e

endpoint=https://content.dropboxapi.com/2/files/upload
tokenpath=$HOME/.creds/dropbox.token

curl \
	-X POST $endpoint \
	--header "Authorization: Bearer $(cat "$tokenpath")" \
	--header "Dropbox-API-Arg: {\"path\": \"/$(basename "$1")\"}" \
	--header "Content-Type: application/octet-stream" \
	--data-binary "@$1" \
| jq
