#!/bin/sh

set -e

die() {
	echo "$@" 1>&2
	exit 1
}

while getopts ":n:" opt; do
	case $opt in
		n ) filename=$OPTARG;;
		: ) echo "-$OPTARG requires an argument" >&2; exit 1;;
		\?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
	esac
done

shift $((OPTIND - 1))

[ "$1" = "" ] && die "Missing argument"
[ ! -f "$1" ] && die "Missing file"

endpoint=https://content.dropboxapi.com/2/files/upload
tokenpath=$HOME/.creds/dropbox.token

[ "$filename" = "" ] && filename=$(basename "$1")
apiarg=$(jq -c --null-input --arg path "/$filename" '.path |= $path')

curl \
	--progress-bar \
	-X POST $endpoint \
	--header "Authorization: Bearer $(cat "$tokenpath")" \
	--header "Dropbox-API-Arg: $apiarg" \
	--header "Content-Type: application/octet-stream" \
	-T "$1" \
| jq
